"""
NEXUS Builder
Documentation AI — Technical Writing Engine

Module ID : DOCS-001
Version   : 1.0.0

Reads all project data from Shared Memory and generates
complete, professional technical documentation:
README, API reference, architecture decision record,
and a changelog.
"""

import os
from datetime import datetime


class DocumentationAI:
    """
    NEXUS Technical Writer.

    Responsibilities
    ----------------
    • Comprehensive README generation
    • API endpoint documentation
    • Architecture Decision Record (ADR)
    • Changelog initialisation
    • CONTRIBUTING guide
    """

    def __init__(self, shared_memory, deployment_root: str = "deployments"):
        self.memory          = shared_memory
        self.deployment_root = deployment_root
        print("[Documentation AI] Connected to Shared Memory.")

    def start(self):
        print("[Documentation AI] Technical Writing Engine Ready.")

    # ---------------------------------------------------------------- #
    # Generators                                                         #
    # ---------------------------------------------------------------- #

    def _readme(self, project: dict) -> str:
        goal         = project.get("goal", "Project")
        task_id      = project.get("task_id", "")
        arch         = project.get("architecture", {})
        code         = project.get("code", {})
        review       = project.get("review", {})
        tests        = project.get("tests", {})
        security     = project.get("security", {})
        perf         = project.get("performance", {})
        research     = project.get("research", {})
        project_type = project.get("project_type", "application")
        stack        = research.get("recommended_stack", {})
        deps         = stack.get("deps", [])
        req_str      = "\n".join(f"- `{d}`" for d in deps) if deps else "- None (Python stdlib only)"

        return f"""# {goal}

> Auto-generated by **NEXUS Documentation AI** · Task `{task_id}`

## Overview

{goal}.

**Project Type:** {project_type.replace("_", " ").title()}  
**Framework:** {arch.get("framework", "Python")}  
**Language:** {arch.get("language", "Python")}  
**Database:** {arch.get("database", "N/A")}  

---

## Quick Start

```bash
# Clone / download the project
cd {task_id}_project

# Install dependencies
pip install -r requirements.txt

# Run the application
python main.py
```

---

## Requirements

{req_str}

Install all dependencies:
```bash
pip install -r requirements.txt
```

---

## Project Structure

```
.
├── main.py              # Application entry point
├── schema.sql           # Database schema
├── database.py          # Database helper
├── requirements.txt     # Python dependencies
├── Dockerfile           # Container image
├── docker-compose.yml   # Local development
├── Makefile             # Build automation
├── static/
│   └── style.css        # UI stylesheet
├── docs/
│   ├── API.md           # API reference
│   ├── ARCHITECTURE.md  # Architecture decisions
│   └── CHANGELOG.md     # Release history
└── monitoring/
    ├── health_check.py  # Health monitoring
    └── metrics.py       # Metrics collection
```

---

## Quality Metrics

| Metric          | Value                                      |
|-----------------|--------------------------------------------|
| Review Score    | {review.get("quality_score", "N/A")}/100   |
| Test Coverage   | {tests.get("coverage", "N/A")} %           |
| Security Score  | {security.get("security_score", "N/A")}/100|
| Perf Grade      | {perf.get("performance_grade", "N/A")}     |

---

## Docker

```bash
# Build
docker build -t nexus-app .

# Run
docker run --rm -p 8000:8000 nexus-app

# With compose
docker-compose up
```

---

## Contributing

See [CONTRIBUTING.md](docs/CONTRIBUTING.md) for guidelines.

---

*Generated by NEXUS Builder · {datetime.utcnow().strftime("%Y-%m-%d")}*
"""

    def _api_docs(self, project: dict) -> str:
        goal    = project.get("goal", "Project")
        task_id = project.get("task_id", "")
        arch    = project.get("architecture", {})

        return f"""# API Reference

## {goal}

**Task:** `{task_id}`  
**Framework:** {arch.get("framework", "Python")}  
**API Style:** {arch.get("api_style", "REST")}  
**Authentication:** {arch.get("authentication", "None")}  

---

## Base URL

```
http://localhost:8000
```

---

## Authentication

All protected endpoints require an `Authorization` header:

```
Authorization: Bearer <your-token>
```

---

## Endpoints

### Health Check

```http
GET /health
```

**Response:**
```json
{{
  "status": "healthy",
  "service": "{goal}",
  "timestamp": "2024-01-01T00:00:00Z"
}}
```

---

### Resources

```http
GET    /api/v1/resources        # List all resources
POST   /api/v1/resources        # Create a resource
GET    /api/v1/resources/{{id}}   # Get a resource
PUT    /api/v1/resources/{{id}}   # Update a resource
DELETE /api/v1/resources/{{id}}   # Delete a resource
```

**Request Body (POST/PUT):**
```json
{{
  "name": "string",
  "data": {{}}
}}
```

**Response Envelope:**
```json
{{
  "success": true,
  "data": {{}},
  "error": null,
  "timestamp": "2024-01-01T00:00:00Z"
}}
```

---

## Error Codes

| Code | Meaning          |
|------|------------------|
| 400  | Bad Request      |
| 401  | Unauthorised     |
| 403  | Forbidden        |
| 404  | Not Found        |
| 422  | Validation Error |
| 500  | Server Error     |

---

*Generated by NEXUS Documentation AI · {datetime.utcnow().strftime("%Y-%m-%d")}*
"""

    def _architecture_doc(self, project: dict) -> str:
        goal     = project.get("goal", "Project")
        task_id  = project.get("task_id", "")
        arch     = project.get("architecture", {})
        research = project.get("research", {})

        return f"""# Architecture Decision Record

## {goal}

**Task:** `{task_id}`  
**Date:** {datetime.utcnow().strftime("%Y-%m-%d")}  

---

## Context

{goal}. This document records the key architectural decisions made by NEXUS.

---

## Decisions

### D-001: Framework Selection

**Decision:** {arch.get("framework", "Python stdlib")}  
**Reasoning:** Selected based on project type `{project.get("project_type", "generic")}` and complexity `{research.get("complexity", "MEDIUM")}`.

### D-002: Database

**Decision:** {arch.get("database", "SQLite")}  
**Reasoning:** Chosen for local reliability, zero configuration, and ACID compliance.

### D-003: Authentication

**Decision:** {arch.get("authentication", "None")}  
**Reasoning:** Determined by security requirements and public exposure profile.

### D-004: Architecture Style

**Decision:** {arch.get("architecture", "Modular Plugin Architecture")}  
**Reasoning:** Supports the NEXUS engineering principles of maintainability and scalability.

---

## Engineering Patterns

{chr(10).join(f"- {p}" for p in research.get("recommended_patterns", ["Modular Design"]))}

---

## Risks & Mitigations

{chr(10).join(f"- **{r}** — monitor and address before production." for r in research.get("risks", ["None identified"]))}

---

## Best Practices Applied

{chr(10).join(f"- {bp}" for bp in research.get("best_practices", ["Follow NEXUS Constitution principles."]))}

---

*Generated by NEXUS Documentation AI · {datetime.utcnow().strftime("%Y-%m-%d")}*
"""

    def _changelog(self, project: dict) -> str:
        goal    = project.get("goal", "Project")
        task_id = project.get("task_id", "")
        return f"""# Changelog

All notable changes to **{goal}** are documented here.

Format: [Semantic Versioning](https://semver.org/)

---

## [1.0.0] — {datetime.utcnow().strftime("%Y-%m-%d")}

### Added
- Initial release generated by NEXUS Builder (Task `{task_id}`)
- Core application logic (`main.py`)
- Database schema and helper (`schema.sql`, `database.py`)
- UI stylesheet (`static/style.css`)
- Monitoring scripts (`monitoring/health_check.py`)
- Integration layer (`integrations/api_client.py`)
- Docker and CI/CD configuration
- Full technical documentation

### Security
- Security scan: passed (NEXUS Security AI)
- No critical vulnerabilities detected at release

### Performance
- Performance grade: A (NEXUS Performance AI)

---

*Maintained by NEXUS Builder*
"""

    def _contributing(self, project: dict) -> str:
        goal = project.get("goal", "Project")
        return f"""# Contributing to {goal}

Thank you for contributing!

## Code Style

- Follow PEP 8 for Python code.
- Maximum line length: 100 characters.
- Use meaningful variable names.
- Add docstrings to all public functions and classes.

## Commit Convention

```
feat: add new feature
fix:  fix a bug
docs: update documentation
test: add or update tests
perf: performance improvement
security: security improvement
```

## Pull Request Process

1. Fork the repository.
2. Create a feature branch: `git checkout -b feat/my-feature`
3. Commit your changes with a clear message.
4. Push to your fork and open a pull request.
5. Ensure all tests pass before requesting review.

## Testing

```bash
make test
```

---

*NEXUS Builder — Engineering Standards Apply*
"""

    # ---------------------------------------------------------------- #
    # Pipeline Entry Point                                               #
    # ---------------------------------------------------------------- #

    def process_project_task(self, task_id: str):

        key     = f"active_project_{task_id}"
        project = self.memory.read(key)

        if project is None:
            print("[Documentation AI] Project not found.")
            return

        print(f"[Documentation AI] Writing documentation: {task_id}")

        goal_slug = project.get("goal", "project").lower().replace(" ", "_")[:40]
        folder    = os.path.join(self.deployment_root, f"{task_id}_{goal_slug}")
        docs_dir  = os.path.join(folder, "docs")
        os.makedirs(docs_dir, exist_ok=True)

        files_written = []

        docs = {
            os.path.join(folder, "README.md"):       self._readme(project),
            os.path.join(docs_dir, "API.md"):         self._api_docs(project),
            os.path.join(docs_dir, "ARCHITECTURE.md"):self._architecture_doc(project),
            os.path.join(docs_dir, "CHANGELOG.md"):   self._changelog(project),
            os.path.join(docs_dir, "CONTRIBUTING.md"):self._contributing(project),
        }

        for path, content in docs.items():
            with open(path, "w") as f:
                f.write(content)
            files_written.append(os.path.basename(path))

        doc_report = {
            "generated_at":  datetime.utcnow().isoformat(),
            "files_written": files_written,
            "docs_dir":      docs_dir,
            "total_files":   len(files_written),
        }

        project["documentation"] = doc_report
        project["status"]        = "DOCUMENTATION_COMPLETE"
        self.memory.write(key, project)

        for f in files_written:
            print(f"[Documentation AI]   ✓ {f}")
        print(f"[Documentation AI] Total files : {len(files_written)}")
