"""
NEXUS Builder
Integration AI — Service Integration Engine

Module ID : INTEGRATION-001
Version   : 1.0.0

Analyses the project architecture and generates integration
artefacts: an HTTP API client, a webhook handler, a service
connector configuration, and an integration README.
"""

import os
import json
from datetime import datetime


def _api_client(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    arch = project.get("architecture", {})
    auth = arch.get("authentication", "None")

    auth_section = ""
    if auth and auth.lower() not in ("none", "n/a", ""):
        auth_section = """
    def _get_headers(self) -> dict:
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if self.api_key:
            headers["Authorization"] = f"Bearer {self.api_key}"
        return headers
"""
    else:
        auth_section = """
    def _get_headers(self) -> dict:
        return {"Content-Type": "application/json", "Accept": "application/json"}
"""

    return f'''\
"""
API Client — Auto-generated by NEXUS Integration AI
Application: {goal}
Authentication: {auth}
"""

import json
import time
import urllib.request
import urllib.error
from typing import Any


class APIClient:
    """
    HTTP client for {goal}.

    Supports GET, POST, PUT, DELETE with automatic retries,
    timeout handling, and structured error responses.
    """

    def __init__(
        self,
        base_url: str = "http://localhost:8000",
        api_key:  str = "",
        timeout:  int = 30,
        retries:  int = 3,
    ):
        self.base_url = base_url.rstrip("/")
        self.api_key  = api_key
        self.timeout  = timeout
        self.retries  = retries
{auth_section}
    def _request(
        self,
        method:  str,
        path:    str,
        payload: Any = None,
    ) -> dict:
        url  = f"{{self.base_url}}{{path}}"
        data = json.dumps(payload).encode() if payload else None
        req  = urllib.request.Request(
            url,
            data=data,
            headers=self._get_headers(),
            method=method,
        )
        for attempt in range(1, self.retries + 1):
            try:
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    body = resp.read().decode()
                    return {{"ok": True, "status": resp.status, "data": json.loads(body)}}
            except urllib.error.HTTPError as err:
                body = err.read().decode()
                if attempt == self.retries:
                    return {{"ok": False, "status": err.code, "error": body}}
                time.sleep(2 ** attempt)
            except Exception as err:
                if attempt == self.retries:
                    return {{"ok": False, "status": 0, "error": str(err)}}
                time.sleep(2 ** attempt)
        return {{"ok": False, "status": 0, "error": "Max retries exceeded"}}

    def get(self, path: str) -> dict:
        return self._request("GET", path)

    def post(self, path: str, payload: Any = None) -> dict:
        return self._request("POST", path, payload)

    def put(self, path: str, payload: Any = None) -> dict:
        return self._request("PUT", path, payload)

    def delete(self, path: str) -> dict:
        return self._request("DELETE", path)

    def health(self) -> dict:
        return self.get("/health")


if __name__ == "__main__":
    client = APIClient()
    result = client.health()
    print("Health:", result)
'''


def _webhook_handler(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    return f'''\
"""
Webhook Handler — Auto-generated by NEXUS Integration AI
Application: {goal}
"""

import json
import hashlib
import hmac
from http.server import BaseHTTPRequestHandler, HTTPServer


WEBHOOK_SECRET = b"change_this_secret_in_production"


def verify_signature(payload: bytes, signature: str) -> bool:
    """Verify HMAC-SHA256 webhook signature."""
    expected = hmac.new(WEBHOOK_SECRET, payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(f"sha256={{expected}}", signature)


def handle_event(event_type: str, payload: dict) -> dict:
    """Route webhook events to handlers."""
    handlers = {{
        "created": on_created,
        "updated": on_updated,
        "deleted": on_deleted,
        "completed": on_completed,
    }}
    handler = handlers.get(event_type)
    if handler:
        return handler(payload)
    return {{"status": "ignored", "event": event_type}}


def on_created(payload: dict) -> dict:
    print(f"[Webhook] Created: {{payload.get('id')}}")
    return {{"status": "processed", "action": "created"}}


def on_updated(payload: dict) -> dict:
    print(f"[Webhook] Updated: {{payload.get('id')}}")
    return {{"status": "processed", "action": "updated"}}


def on_deleted(payload: dict) -> dict:
    print(f"[Webhook] Deleted: {{payload.get('id')}}")
    return {{"status": "processed", "action": "deleted"}}


def on_completed(payload: dict) -> dict:
    print(f"[Webhook] Completed: {{payload.get('id')}}")
    return {{"status": "processed", "action": "completed"}}


class WebhookHandler(BaseHTTPRequestHandler):

    def log_message(self, fmt, *args):
        print(f"[Webhook Server] {{fmt % args}}")

    def do_POST(self):
        length  = int(self.headers.get("Content-Length", 0))
        body    = self.rfile.read(length)
        sig     = self.headers.get("X-Signature", "")

        if not verify_signature(body, sig):
            self.send_response(401)
            self.end_headers()
            self.wfile.write(b"Unauthorised")
            return

        try:
            data       = json.loads(body)
            event_type = data.get("event", "unknown")
            result     = handle_event(event_type, data.get("payload", {{}}))
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(result).encode())
        except Exception as err:
            self.send_response(500)
            self.end_headers()
            self.wfile.write(str(err).encode())


if __name__ == "__main__":
    server = HTTPServer(("0.0.0.0", 9000), WebhookHandler)
    print(f"Webhook server listening on port 9000")
    server.serve_forever()
'''


def _integration_config(project: dict) -> dict:
    arch = project.get("architecture", {})
    return {
        "app":       project.get("goal", "NEXUS Application"),
        "generated": datetime.utcnow().isoformat(),
        "api": {
            "base_url": "http://localhost:8000",
            "version":  "v1",
            "timeout":  30,
            "retries":  3,
            "auth_type": arch.get("authentication", "none").lower(),
        },
        "webhook": {
            "port":         9000,
            "path":         "/webhook",
            "secret_env":   "WEBHOOK_SECRET",
            "verify_sig":   True,
            "events": ["created", "updated", "deleted", "completed"],
        },
        "services": {
            "database": {
                "type": arch.get("database", "sqlite"),
                "path": "data/database.sqlite",
            },
        },
    }


def _integration_readme(project: dict) -> str:
    goal = project.get("goal", "Project")
    return f"""# Integration Guide

## {goal}

---

## API Client

```python
from integrations.api_client import APIClient

client = APIClient(
    base_url="http://localhost:8000",
    api_key="your-api-key",   # if required
)

# Health check
print(client.health())

# CRUD operations
result = client.get("/api/v1/resources")
result = client.post("/api/v1/resources", {{"name": "item"}})
result = client.put("/api/v1/resources/1", {{"name": "updated"}})
result = client.delete("/api/v1/resources/1")
```

---

## Webhook Handler

Start the webhook server:
```bash
python integrations/webhook_handler.py
```

Send a test webhook:
```bash
curl -X POST http://localhost:9000 \\
  -H "Content-Type: application/json" \\
  -H "X-Signature: sha256=<hmac>" \\
  -d '{{"event":"created","payload":{{"id":1}}}}'
```

---

## Configuration

Edit `integrations/config.json` to customise endpoints,
timeouts, auth settings, and webhook event subscriptions.

---

*Generated by NEXUS Integration AI*
"""


class IntegrationAI:
    """
    NEXUS Integration Engineer.

    Generates a complete integration layer: HTTP client,
    webhook handler, service configuration, and guide.
    """

    def __init__(self, shared_memory, deployment_root: str = "deployments"):
        self.memory          = shared_memory
        self.deployment_root = deployment_root
        print("[Integration AI] Connected to Shared Memory.")

    def start(self):
        print("[Integration AI] Service Integration Engine Ready.")

    def process_project_task(self, task_id: str):

        key     = f"active_project_{task_id}"
        project = self.memory.read(key)

        if project is None:
            print("[Integration AI] Project not found.")
            return

        print(f"[Integration AI] Generating integration layer: {task_id}")

        goal_slug = project.get("goal", "project").lower().replace(" ", "_")[:40]
        folder    = os.path.join(self.deployment_root, f"{task_id}_{goal_slug}")
        int_dir   = os.path.join(folder, "integrations")
        os.makedirs(int_dir, exist_ok=True)

        config = _integration_config(project)

        artefacts = {
            os.path.join(int_dir, "api_client.py"):      _api_client(project),
            os.path.join(int_dir, "webhook_handler.py"): _webhook_handler(project),
            os.path.join(int_dir, "README.md"):           _integration_readme(project),
            os.path.join(int_dir, "config.json"):         json.dumps(config, indent=2),
            os.path.join(int_dir, "__init__.py"):         "",
        }

        written = []
        for path, content in artefacts.items():
            with open(path, "w") as f:
                f.write(content)
            written.append(os.path.basename(path))

        int_report = {
            "generated_at":    datetime.utcnow().isoformat(),
            "artefacts":       written,
            "integration_dir": int_dir,
            "integration_points": ["REST API", "Webhooks", "Database"],
        }

        project["integration"] = int_report
        project["status"]      = "INTEGRATION_COMPLETE"
        self.memory.write(key, project)

        for a in written:
            print(f"[Integration AI]   ✓ {a}")
        print(f"[Integration AI] Integration points: REST API, Webhooks, Database")
