"""
NEXUS Builder
Coder AI — Development Node

Module ID : CODER-001
Version   : 0.2.0
"""

from datetime import datetime


# ------------------------------------------------------------------ #
# Source Code Templates                                               #
# ------------------------------------------------------------------ #

_CALCULATOR_SOURCE = '''"""
Auto-generated by NEXUS Coder AI
Goal: Calculator Application
"""


def add(a, b):
    """Return the sum of a and b."""
    return a + b


def subtract(a, b):
    """Return the difference of a and b."""
    return a - b


def multiply(a, b):
    """Return the product of a and b."""
    return a * b


def divide(a, b):
    """Return the quotient of a and b. Raises ValueError on division by zero."""
    if b == 0:
        raise ValueError("Cannot divide by zero.")
    return a / b


def calculate(expression: str):
    """
    Parse and evaluate a simple arithmetic expression string.
    Supported operators: + - * /
    Example: calculate("10 + 5") -> 15.0
    """
    parts = expression.strip().split()

    if len(parts) != 3:
        raise ValueError(
            f"Invalid expression '{expression}'. "
            "Expected format: <number> <operator> <number>"
        )

    left, operator, right = parts

    left  = float(left)
    right = float(right)

    if operator == "+":
        return add(left, right)
    elif operator == "-":
        return subtract(left, right)
    elif operator == "*":
        return multiply(left, right)
    elif operator == "/":
        return divide(left, right)
    else:
        raise ValueError(f"Unknown operator: {operator}")


def run_repl():
    """Interactive calculator loop."""
    print("=" * 40)
    print("NEXUS Calculator")
    print("Format : <number> <operator> <number>")
    print("Example: 10 + 5")
    print("Type 'exit' to quit.")
    print("=" * 40)

    while True:
        try:
            expression = input("calc> ").strip()

            if expression.lower() == "exit":
                print("Goodbye.")
                break

            result = calculate(expression)
            print(f"= {result}")

        except (ValueError, ZeroDivisionError) as error:
            print(f"[Error] {error}")


if __name__ == "__main__":
    run_repl()
'''

_API_SOURCE = '''"""
Auto-generated by NEXUS Coder AI
"""


def initialize_local_api():
    """
    Initializes the isolated local API.
    """
    system_status = "ONLINE"
    return True, f"E-Commerce Endpoint state locked: {system_status}"


def health_check():
    """
    Returns service health.
    """
    return {
        "status": "healthy",
        "service": "NEXUS Local API"
    }


if __name__ == "__main__":
    success, message = initialize_local_api()
    print(message)
'''


def _select_template(goal: str) -> str:
    """Choose a source template based on keywords in the goal."""
    goal_lower = goal.lower()

    if any(kw in goal_lower for kw in ["calculator", "calc", "arithmetic", "math"]):
        return _CALCULATOR_SOURCE

    # Default: generic local API
    return _API_SOURCE


# ------------------------------------------------------------------ #
# CoderAI                                                             #
# ------------------------------------------------------------------ #

class CoderAI:
    """
    The software engineering worker of NEXUS.

    Responsibilities:
    - Generate executable source code
    - Commit code artifacts into Shared Memory
    - Prepare projects for automated review
    """

    def __init__(self, shared_memory):
        self.memory = shared_memory
        print("[Coder AI] Connected to Shared Memory.")

    def start(self):
        print("[Coder AI] Ready.")

    def process_project_task(self, task_id: str):

        project_key = f"active_project_{task_id}"
        project = self.memory.read(project_key)

        if project is None:
            print(f"[Coder AI] Error: Project '{task_id}' not found.")
            return

        print(f"[Coder AI] Processing Task: {task_id}")
        print(f"[Coder AI] Goal: {project['goal']}")

        # ----------------------------------------------------------
        # Select and generate source code based on the project goal
        # ----------------------------------------------------------

        generated_source = _select_template(project["goal"])

        # ----------------------------------------------------------
        # Store code artifact
        # ----------------------------------------------------------

        project["code"] = {
            "language": "Python",
            "version": "0.1.0",
            "author": "Coder AI",
            "generated_at": datetime.utcnow().isoformat(),
            "status": "INITIAL_IMPLEMENTATION_COMPLETE",
            "files": [
                "main.py"
            ],
            "source": generated_source
        }

        project["status"] = "PROGRAMMING_PHASE_COMPLETE"

        self.memory.write(project_key, project)

        print("[Coder AI] Executable source generated.")
        print("[Coder AI] Shared Memory Updated.")
