"""
NEXUS Builder
Coder AI — Universal Code Generation Engine

Module ID : CODER-001
Version   : 2.0.0

Generates complete, production-grade applications for any
project type detected by Research AI.  Every template is
runnable Python with proper structure, error handling, and
documentation.
"""

from datetime import datetime


# ------------------------------------------------------------------ #
# Project Type → Requirements Mapping                                  #
# ------------------------------------------------------------------ #

_REQUIREMENTS: dict = {
    "calculator":    [],
    "todo_app":      [],
    "web_app":       ["flask>=3.0.0"],
    "rest_api":      ["fastapi>=0.110.0", "uvicorn>=0.29.0"],
    "desktop_gui":   [],
    "data_analyzer": [],
    "game":          [],
    "chat_app":      [],
    "inventory":     [],
    "ai_system":     [],
    "scheduler":     [],
    "file_manager":  [],
    "generic":       [],
}


# ================================================================== #
# SOURCE CODE TEMPLATES                                                #
# ================================================================== #

_TEMPLATES: dict = {

# ------------------------------------------------------------------ #
"calculator": '''\
"""
Calculator Application
Auto-generated by NEXUS Coder AI
"""

from decimal import Decimal, InvalidOperation


def add(a, b):
    """Return the sum of a and b."""
    return Decimal(str(a)) + Decimal(str(b))


def subtract(a, b):
    """Return the difference of a and b."""
    return Decimal(str(a)) - Decimal(str(b))


def multiply(a, b):
    """Return the product of a and b."""
    return Decimal(str(a)) * Decimal(str(b))


def divide(a, b):
    """Return the quotient of a and b. Raises ValueError on division by zero."""
    if Decimal(str(b)) == 0:
        raise ValueError("Cannot divide by zero.")
    return Decimal(str(a)) / Decimal(str(b))


def calculate(expression: str):
    """
    Evaluate a simple arithmetic expression string.
    Format: <number> <operator> <number>
    Example: calculate("10 + 5") -> Decimal('15')
    """
    parts = expression.strip().split()
    if len(parts) != 3:
        raise ValueError(f"Invalid expression: '{expression}'. Use: <num> <op> <num>")
    left, op, right = parts
    try:
        l, r = Decimal(left), Decimal(right)
    except InvalidOperation:
        raise ValueError(f"Invalid numbers: {left}, {right}")
    ops = {"+": add, "-": subtract, "*": multiply, "/": divide}
    if op not in ops:
        raise ValueError(f"Unknown operator: {op}. Use +, -, *, /")
    return ops[op](l, r)


def history_session():
    """Return an empty history list for a session."""
    return []


def run_repl():
    """Interactive calculator REPL."""
    print("=" * 40)
    print("  NEXUS Calculator")
    print("  Format : <num> <op> <num>")
    print("  Type 'history' or 'exit'")
    print("=" * 40)
    history = history_session()
    while True:
        try:
            expr = input("calc> ").strip()
            if expr.lower() == "exit":
                break
            if expr.lower() == "history":
                for i, h in enumerate(history, 1):
                    print(f"  {i}. {h}")
                continue
            result = calculate(expr)
            print(f"  = {result}")
            history.append(f"{expr} = {result}")
        except (ValueError, KeyboardInterrupt, EOFError) as e:
            if isinstance(e, (KeyboardInterrupt, EOFError)):
                break
            print(f"  Error: {e}")


if __name__ == "__main__":
    run_repl()
''',

# ------------------------------------------------------------------ #
"todo_app": '''\
"""
Task Manager Application
Auto-generated by NEXUS Coder AI
"""

import json
import uuid
from datetime import datetime
from pathlib import Path

DATA_FILE = Path("tasks.json")


def load_tasks() -> list:
    """Load all tasks from persistent storage."""
    if not DATA_FILE.exists():
        return []
    try:
        with open(DATA_FILE) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return []


def save_tasks(tasks: list) -> None:
    """Persist tasks to storage using atomic write."""
    tmp = DATA_FILE.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(tasks, f, indent=2)
    tmp.replace(DATA_FILE)


def create_task(title: str, priority: str = "MEDIUM", due_date: str = "") -> dict:
    """Create and persist a new task. Returns the created task."""
    if not title.strip():
        raise ValueError("Task title cannot be empty.")
    priority = priority.upper()
    if priority not in ("LOW", "MEDIUM", "HIGH", "CRITICAL"):
        priority = "MEDIUM"
    task = {
        "id":         str(uuid.uuid4())[:8],
        "title":      title.strip(),
        "status":     "PENDING",
        "priority":   priority,
        "due_date":   due_date,
        "created_at": datetime.utcnow().isoformat(),
        "updated_at": datetime.utcnow().isoformat(),
    }
    tasks = load_tasks()
    tasks.append(task)
    save_tasks(tasks)
    return task


def list_tasks(status: str = "") -> list:
    """Return all tasks, optionally filtered by status."""
    tasks = load_tasks()
    if status:
        tasks = [t for t in tasks if t["status"] == status.upper()]
    return sorted(tasks, key=lambda t: ("LOW","MEDIUM","HIGH","CRITICAL").index(t.get("priority","MEDIUM")), reverse=True)


def complete_task(task_id: str) -> bool:
    """Mark a task as DONE. Returns True if found."""
    tasks = load_tasks()
    for task in tasks:
        if task["id"] == task_id:
            task["status"]     = "DONE"
            task["updated_at"] = datetime.utcnow().isoformat()
            save_tasks(tasks)
            return True
    return False


def delete_task(task_id: str) -> bool:
    """Delete a task by ID. Returns True if found."""
    tasks = load_tasks()
    new   = [t for t in tasks if t["id"] != task_id]
    if len(new) == len(tasks):
        return False
    save_tasks(new)
    return True


def get_summary() -> dict:
    """Return task count statistics."""
    tasks = load_tasks()
    return {
        "total":    len(tasks),
        "pending":  sum(1 for t in tasks if t["status"] == "PENDING"),
        "done":     sum(1 for t in tasks if t["status"] == "DONE"),
        "critical": sum(1 for t in tasks if t["priority"] == "CRITICAL"),
    }


def run_repl():
    """Interactive task manager CLI."""
    print("=" * 50)
    print("  NEXUS Task Manager")
    print("  Commands: add, list, done, delete, summary, exit")
    print("=" * 50)
    while True:
        try:
            cmd = input("tasks> ").strip().lower()
            if cmd == "exit":
                break
            elif cmd == "add":
                title    = input("  Title    : ").strip()
                priority = input("  Priority [LOW/MEDIUM/HIGH/CRITICAL]: ").strip() or "MEDIUM"
                task     = create_task(title, priority)
                print(f"  Created: [{task['id']}] {task['title']}")
            elif cmd == "list":
                for t in list_tasks():
                    print(f"  [{t['id']}] {t['priority']:<8} {t['status']:<10} {t['title']}")
            elif cmd == "done":
                tid = input("  Task ID: ").strip()
                print("  ✓ Done" if complete_task(tid) else "  Not found")
            elif cmd == "delete":
                tid = input("  Task ID: ").strip()
                print("  Deleted" if delete_task(tid) else "  Not found")
            elif cmd == "summary":
                s = get_summary()
                print(f"  Total: {s['total']}  Pending: {s['pending']}  Done: {s['done']}  Critical: {s['critical']}")
            else:
                print("  Unknown command.")
        except (KeyboardInterrupt, EOFError):
            break


if __name__ == "__main__":
    run_repl()
''',

# ------------------------------------------------------------------ #
"web_app": '''\
"""
Web Application
Auto-generated by NEXUS Coder AI
Requires: flask>=3.0.0
"""

import os
import json
import hashlib
import secrets
from datetime import datetime
from pathlib import Path

try:
    from flask import Flask, request, jsonify, render_template_string, session, redirect
    FLASK_AVAILABLE = True
except ImportError:
    FLASK_AVAILABLE = False

app = Flask(__name__) if FLASK_AVAILABLE else None

if app:
    app.secret_key = os.environ.get("SECRET_KEY", secrets.token_hex(32))


# ── In-memory store (replace with DB in production) ─────────────── #
_store: dict = {"users": {}, "items": []}

INDEX_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NEXUS Web App</title>
  <link rel="stylesheet" href="/static/style.css">
</head>
<body>
  <nav>
    <span>NEXUS App</span>
    <a href="/api/health">Health</a>
  </nav>
  <div class="container mt-4">
    <div class="card">
      <h1>Welcome to NEXUS Web App</h1>
      <p>Your application is running successfully.</p>
      <a href="/api/health" class="btn btn-primary mt-2">Check Health</a>
    </div>
  </div>
</body>
</html>"""


def get_app_info() -> dict:
    """Return application metadata."""
    return {
        "name":      "NEXUS Web App",
        "version":   "1.0.0",
        "generated": datetime.utcnow().isoformat(),
        "flask":     FLASK_AVAILABLE,
    }


def hash_password(password: str) -> str:
    """One-way hash a password."""
    return hashlib.sha256(password.encode()).hexdigest()


def validate_input(data: dict, required: list) -> list:
    """Return list of missing required fields."""
    return [f for f in required if not data.get(f)]


if app:

    @app.route("/")
    def index():
        return render_template_string(INDEX_HTML)

    @app.route("/api/health")
    def health():
        return jsonify({
            "status":    "healthy",
            "app":       "NEXUS Web App",
            "timestamp": datetime.utcnow().isoformat(),
        })

    @app.route("/api/users", methods=["GET"])
    def list_users():
        return jsonify({"users": list(_store["users"].keys())})

    @app.route("/api/users", methods=["POST"])
    def create_user():
        data    = request.get_json() or {}
        missing = validate_input(data, ["username", "password"])
        if missing:
            return jsonify({"error": f"Missing: {missing}"}), 400
        username = data["username"]
        if username in _store["users"]:
            return jsonify({"error": "User already exists"}), 409
        _store["users"][username] = {
            "username":  username,
            "password":  hash_password(data["password"]),
            "created_at": datetime.utcnow().isoformat(),
        }
        return jsonify({"created": username}), 201

    @app.route("/api/items", methods=["GET"])
    def list_items():
        return jsonify({"items": _store["items"]})

    @app.route("/api/items", methods=["POST"])
    def create_item():
        data    = request.get_json() or {}
        missing = validate_input(data, ["name"])
        if missing:
            return jsonify({"error": f"Missing: {missing}"}), 400
        item = {"id": len(_store["items"]) + 1, "name": data["name"],
                "created_at": datetime.utcnow().isoformat()}
        _store["items"].append(item)
        return jsonify(item), 201

    @app.errorhandler(404)
    def not_found(e):
        return jsonify({"error": "Not found"}), 404

    @app.errorhandler(500)
    def server_error(e):
        return jsonify({"error": "Internal server error"}), 500


def create_app():
    """Application factory."""
    return app


if __name__ == "__main__":
    if not FLASK_AVAILABLE:
        print("Flask not installed. Run: pip install flask")
    else:
        info = get_app_info()
        print(f"Starting {info[\'name\']} v{info[\'version\']}")
        app.run(host="0.0.0.0", port=5000, debug=False)
''',

# ------------------------------------------------------------------ #
"rest_api": '''\
"""
REST API
Auto-generated by NEXUS Coder AI
Requires: fastapi>=0.110.0, uvicorn>=0.29.0
"""

import json
import uuid
import hashlib
from datetime import datetime
from typing import Any

try:
    from fastapi import FastAPI, HTTPException, Header
    from fastapi.responses import JSONResponse
    from pydantic import BaseModel
    import uvicorn
    FASTAPI_AVAILABLE = True
except ImportError:
    FASTAPI_AVAILABLE = False
    FastAPI = None

app = FastAPI(
    title="NEXUS REST API",
    version="1.0.0",
    description="Auto-generated by NEXUS Coder AI",
) if FASTAPI_AVAILABLE else None

# ── In-memory data store ────────────────────────────────────────── #
_resources: dict = {}


def generate_id() -> str:
    """Generate a short unique ID."""
    return str(uuid.uuid4())[:8]


def get_timestamp() -> str:
    """Return current UTC timestamp."""
    return datetime.utcnow().isoformat()


def build_response(data: Any, success: bool = True) -> dict:
    """Build a standardised API response envelope."""
    return {
        "success":   success,
        "data":      data,
        "timestamp": get_timestamp(),
    }


def validate_resource(data: dict) -> list:
    """Return list of validation errors."""
    errors = []
    if not data.get("name", "").strip():
        errors.append("name is required and cannot be empty")
    return errors


if FASTAPI_AVAILABLE:

    class ResourceIn(BaseModel):
        name: str
        data: dict = {}

    @app.get("/health")
    def health_check():
        return build_response({"status": "healthy", "resources": len(_resources)})

    @app.get("/api/v1/resources")
    def list_resources(limit: int = 50, offset: int = 0):
        items  = list(_resources.values())
        paged  = items[offset: offset + limit]
        return build_response({
            "items":  paged,
            "total":  len(items),
            "limit":  limit,
            "offset": offset,
        })

    @app.post("/api/v1/resources", status_code=201)
    def create_resource(body: ResourceIn):
        resource = {
            "id":         generate_id(),
            "name":       body.name,
            "data":       body.data,
            "created_at": get_timestamp(),
            "updated_at": get_timestamp(),
        }
        _resources[resource["id"]] = resource
        return build_response(resource)

    @app.get("/api/v1/resources/{resource_id}")
    def get_resource(resource_id: str):
        resource = _resources.get(resource_id)
        if not resource:
            raise HTTPException(status_code=404, detail="Resource not found")
        return build_response(resource)

    @app.put("/api/v1/resources/{resource_id}")
    def update_resource(resource_id: str, body: ResourceIn):
        if resource_id not in _resources:
            raise HTTPException(status_code=404, detail="Resource not found")
        _resources[resource_id].update({
            "name":       body.name,
            "data":       body.data,
            "updated_at": get_timestamp(),
        })
        return build_response(_resources[resource_id])

    @app.delete("/api/v1/resources/{resource_id}")
    def delete_resource(resource_id: str):
        if resource_id not in _resources:
            raise HTTPException(status_code=404, detail="Resource not found")
        del _resources[resource_id]
        return build_response({"deleted": resource_id})


def start_server(host: str = "0.0.0.0", port: int = 8000):
    """Start the API server."""
    if not FASTAPI_AVAILABLE:
        print("FastAPI not installed. Run: pip install fastapi uvicorn")
        return
    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    start_server()
''',

# ------------------------------------------------------------------ #
"desktop_gui": '''\
"""
Desktop GUI Application
Auto-generated by NEXUS Coder AI
Uses: tkinter (Python stdlib)
"""

import tkinter as tk
from tkinter import ttk, messagebox, simpledialog
from datetime import datetime


class NexusApp(tk.Tk):
    """Main application window."""

    APP_NAME = "NEXUS Desktop App"
    VERSION  = "1.0.0"

    def __init__(self):
        super().__init__()
        self.title(f"{self.APP_NAME} v{self.VERSION}")
        self.geometry("800x600")
        self.minsize(600, 400)
        self.configure(bg="#F0F4F8")
        self._items: list = []
        self._build_ui()
        self._status("Application started.")

    def _build_ui(self):
        """Construct all UI components."""
        self._build_menu()
        self._build_toolbar()
        self._build_main()
        self._build_statusbar()

    def _build_menu(self):
        menubar = tk.Menu(self)
        file_menu = tk.Menu(menubar, tearoff=0)
        file_menu.add_command(label="New Item",  command=self._add_item, accelerator="Ctrl+N")
        file_menu.add_separator()
        file_menu.add_command(label="Exit",      command=self.quit)
        menubar.add_cascade(label="File",  menu=file_menu)

        edit_menu = tk.Menu(menubar, tearoff=0)
        edit_menu.add_command(label="Delete Selected", command=self._delete_item)
        edit_menu.add_command(label="Clear All",       command=self._clear_all)
        menubar.add_cascade(label="Edit",  menu=edit_menu)

        help_menu = tk.Menu(menubar, tearoff=0)
        help_menu.add_command(label="About", command=self._about)
        menubar.add_cascade(label="Help",  menu=help_menu)

        self.config(menu=menubar)
        self.bind("<Control-n>", lambda _: self._add_item())

    def _build_toolbar(self):
        bar = tk.Frame(self, bg="#264653", pady=4)
        bar.pack(fill=tk.X)

        tk.Label(bar, text=self.APP_NAME, bg="#264653", fg="white",
                 font=("Segoe UI", 12, "bold")).pack(side=tk.LEFT, padx=10)

        tk.Button(bar, text="+ Add",    command=self._add_item,
                  bg="#2A9D8F", fg="white", relief=tk.FLAT,
                  padx=8, pady=2).pack(side=tk.LEFT, padx=4)
        tk.Button(bar, text="✕ Delete", command=self._delete_item,
                  bg="#E76F51", fg="white", relief=tk.FLAT,
                  padx=8, pady=2).pack(side=tk.LEFT, padx=4)

    def _build_main(self):
        frame = tk.Frame(self, bg="#F0F4F8", padx=10, pady=10)
        frame.pack(fill=tk.BOTH, expand=True)

        # Left: list
        left = tk.LabelFrame(frame, text=" Items ", bg="#F0F4F8",
                              font=("Segoe UI", 10))
        left.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(0, 5))

        self._listbox = tk.Listbox(left, font=("Segoe UI", 10),
                                    selectmode=tk.SINGLE, bd=0,
                                    highlightthickness=1)
        self._listbox.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)
        self._listbox.bind("<<ListboxSelect>>", self._on_select)

        # Right: detail
        right = tk.LabelFrame(frame, text=" Detail ", bg="#F0F4F8",
                               font=("Segoe UI", 10), width=250)
        right.pack(side=tk.RIGHT, fill=tk.Y, padx=(5, 0))
        right.pack_propagate(False)

        self._detail = tk.Text(right, font=("Segoe UI", 10), bd=0,
                                state=tk.DISABLED, wrap=tk.WORD,
                                bg="#FFFFFF", pady=5, padx=5)
        self._detail.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

    def _build_statusbar(self):
        self._status_var = tk.StringVar(value="Ready")
        bar = tk.Label(self, textvariable=self._status_var, anchor=tk.W,
                       bg="#264653", fg="white", padx=8)
        bar.pack(fill=tk.X, side=tk.BOTTOM)

    # ── Actions ──────────────────────────────────────────────────── #

    def _add_item(self):
        name = simpledialog.askstring("New Item", "Enter item name:", parent=self)
        if name and name.strip():
            item = {"name": name.strip(), "created_at": datetime.now().isoformat()}
            self._items.append(item)
            self._listbox.insert(tk.END, item["name"])
            self._status(f"Added: {item['name']}")

    def _delete_item(self):
        sel = self._listbox.curselection()
        if not sel:
            messagebox.showinfo("Delete", "Select an item first.")
            return
        idx  = sel[0]
        name = self._items[idx]["name"]
        self._items.pop(idx)
        self._listbox.delete(idx)
        self._clear_detail()
        self._status(f"Deleted: {name}")

    def _clear_all(self):
        if messagebox.askyesno("Clear All", "Delete all items?"):
            self._items.clear()
            self._listbox.delete(0, tk.END)
            self._clear_detail()
            self._status("All items cleared.")

    def _on_select(self, _event):
        sel = self._listbox.curselection()
        if not sel:
            return
        item = self._items[sel[0]]
        self._detail.config(state=tk.NORMAL)
        self._detail.delete("1.0", tk.END)
        self._detail.insert(tk.END,
            f"Name:       {item['name']}\n"
            f"Created:    {item['created_at']}\n"
        )
        self._detail.config(state=tk.DISABLED)

    def _clear_detail(self):
        self._detail.config(state=tk.NORMAL)
        self._detail.delete("1.0", tk.END)
        self._detail.config(state=tk.DISABLED)

    def _about(self):
        messagebox.showinfo("About",
            f"{self.APP_NAME}\nVersion {self.VERSION}\n\nGenerated by NEXUS Builder")

    def _status(self, msg: str):
        self._status_var.set(f"  {msg}")


def get_version() -> str:
    """Return the application version string."""
    return NexusApp.VERSION


def check_tkinter() -> bool:
    """Return True if tkinter is available."""
    try:
        import tkinter  # noqa: F401
        return True
    except ImportError:
        return False


if __name__ == "__main__":
    if check_tkinter():
        app = NexusApp()
        app.mainloop()
    else:
        print("tkinter not available on this system.")
''',

# ------------------------------------------------------------------ #
"data_analyzer": '''\
"""
Data Analysis Tool
Auto-generated by NEXUS Coder AI
Uses: Python stdlib (csv, json, statistics)
"""

import csv
import json
import statistics
from pathlib import Path
from datetime import datetime
from typing import Any


def load_csv(filepath: str) -> list:
    """Load a CSV file and return a list of dicts."""
    path = Path(filepath)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {filepath}")
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def load_json(filepath: str) -> Any:
    """Load a JSON file."""
    with open(filepath, encoding="utf-8") as f:
        return json.load(f)


def describe(data: list, column: str) -> dict:
    """Compute descriptive statistics for a numeric column."""
    values = []
    for row in data:
        try:
            values.append(float(row[column]))
        except (ValueError, KeyError):
            pass
    if not values:
        return {"error": f"No numeric values in column '{column}'"}
    return {
        "column":  column,
        "count":   len(values),
        "mean":    round(statistics.mean(values), 4),
        "median":  round(statistics.median(values), 4),
        "stdev":   round(statistics.stdev(values), 4) if len(values) > 1 else 0,
        "min":     min(values),
        "max":     max(values),
        "sum":     round(sum(values), 4),
    }


def frequency(data: list, column: str) -> dict:
    """Count occurrences of each value in a column."""
    counts: dict = {}
    for row in data:
        val = str(row.get(column, "")).strip()
        counts[val] = counts.get(val, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))


def filter_rows(data: list, column: str, value: str) -> list:
    """Filter rows where column equals value."""
    return [r for r in data if str(r.get(column, "")) == value]


def top_n(data: list, column: str, n: int = 10) -> list:
    """Return top N rows sorted by a numeric column (descending)."""
    def safe_val(r):
        try:
            return float(r.get(column, 0))
        except ValueError:
            return 0.0
    return sorted(data, key=safe_val, reverse=True)[:n]


def export_report(data: list, output_path: str = "report.json") -> str:
    """Export analysis results to JSON."""
    columns  = list(data[0].keys()) if data else []
    num_cols = []
    for col in columns:
        try:
            [float(r[col]) for r in data[:5] if r.get(col)]
            num_cols.append(col)
        except (ValueError, TypeError):
            pass
    report = {
        "generated_at": datetime.utcnow().isoformat(),
        "total_rows":   len(data),
        "columns":      columns,
        "numeric_stats": {col: describe(data, col) for col in num_cols},
    }
    with open(output_path, "w") as f:
        json.dump(report, f, indent=2)
    return output_path


def get_columns(data: list) -> list:
    """Return column names from the dataset."""
    return list(data[0].keys()) if data else []


def run_repl():
    """Interactive data analysis CLI."""
    print("=" * 50)
    print("  NEXUS Data Analyzer")
    print("  Commands: load <file>, describe <col>, freq <col>, top <col> <n>, export, exit")
    print("=" * 50)
    data: list = []
    while True:
        try:
            cmd = input("analyze> ").strip().split(None, 2)
            if not cmd:
                continue
            action = cmd[0].lower()
            if action == "exit":
                break
            elif action == "load" and len(cmd) >= 2:
                data = load_csv(cmd[1])
                print(f"  Loaded {len(data)} rows. Columns: {get_columns(data)}")
            elif action == "describe" and len(cmd) >= 2:
                print(json.dumps(describe(data, cmd[1]), indent=2))
            elif action == "freq" and len(cmd) >= 2:
                freq = frequency(data, cmd[1])
                for k, v in list(freq.items())[:10]:
                    print(f"  {k}: {v}")
            elif action == "top" and len(cmd) >= 2:
                n   = int(cmd[2]) if len(cmd) >= 3 else 5
                for row in top_n(data, cmd[1], n):
                    print(f"  {row}")
            elif action == "export":
                path = export_report(data)
                print(f"  Report saved: {path}")
            else:
                print("  Unknown command or missing argument.")
        except (KeyboardInterrupt, EOFError):
            break
        except Exception as e:
            print(f"  Error: {e}")


if __name__ == "__main__":
    run_repl()
''',

# ------------------------------------------------------------------ #
"game": '''\
"""
Text Adventure Game
Auto-generated by NEXUS Coder AI
"""

import random
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class Player:
    name:   str
    hp:     int = 100
    max_hp: int = 100
    atk:    int = 15
    gold:   int = 0
    level:  int = 1
    xp:     int = 0


@dataclass
class Enemy:
    name:   str
    hp:     int
    atk:    int
    reward_xp:  int
    reward_gold: int


@dataclass
class Room:
    name:        str
    description: str
    enemy:       Optional[Enemy] = None
    treasure:    int = 0
    exits:       dict = field(default_factory=dict)


def create_player(name: str) -> Player:
    """Create a new player character."""
    return Player(name=name)


def create_enemy(difficulty: int = 1) -> Enemy:
    """Spawn a random enemy scaled to difficulty."""
    templates = [
        ("Goblin",   15, 5,  10, 5),
        ("Skeleton", 20, 7,  15, 8),
        ("Orc",      30, 10, 25, 12),
        ("Troll",    45, 13, 40, 20),
    ]
    t = random.choice(templates[:max(1, difficulty)])
    return Enemy(name=t[0], hp=t[1]*difficulty, atk=t[2],
                 reward_xp=t[3], reward_gold=t[4])


def player_attack(player: Player, enemy: Enemy) -> int:
    """Player attacks enemy. Returns damage dealt."""
    dmg = random.randint(player.atk - 5, player.atk + 5)
    dmg = max(1, dmg)
    enemy.hp -= dmg
    return dmg


def enemy_attack(enemy: Enemy, player: Player) -> int:
    """Enemy attacks player. Returns damage dealt."""
    dmg = random.randint(enemy.atk - 3, enemy.atk + 3)
    dmg = max(1, dmg)
    player.hp -= dmg
    return dmg


def combat_round(player: Player, enemy: Enemy) -> str:
    """Execute one full combat round. Returns status string."""
    p_dmg = player_attack(player, enemy)
    log   = f"  You deal {p_dmg} to {enemy.name}. "
    if enemy.hp <= 0:
        player.xp   += enemy.reward_xp
        player.gold += enemy.reward_gold
        log += f"{enemy.name} defeated! +{enemy.reward_xp}XP +{enemy.reward_gold}G"
        if player.xp >= player.level * 50:
            player.level  += 1
            player.max_hp += 10
            player.hp     = min(player.hp + 10, player.max_hp)
            player.atk    += 2
            log += f" *** LEVEL UP! Now level {player.level} ***"
        return log
    e_dmg = enemy_attack(enemy, player)
    log  += f"{enemy.name} deals {e_dmg} to you. HP: {player.hp}/{player.max_hp}"
    return log


def get_player_status(player: Player) -> str:
    """Return a formatted player status string."""
    return (f"[{player.name}] HP:{player.hp}/{player.max_hp} "
            f"ATK:{player.atk} LVL:{player.level} XP:{player.xp} GOLD:{player.gold}")


def run_game():
    """Main game loop."""
    print("=" * 50)
    print("  NEXUS Adventure")
    print("=" * 50)
    try:
        name = input("  Enter your name: ").strip() or "Hero"
    except EOFError:
        name = "Hero"
    player = create_player(name)
    print(f"\n  Welcome, {player.name}! Your quest begins...\n")

    rooms_cleared = 0
    while player.hp > 0:
        try:
            print(get_player_status(player))
            print("\n  [1] Explore  [2] Rest (+20 HP)  [3] Quit")
            choice = input("  Action: ").strip()
        except EOFError:
            break

        if choice == "3":
            break
        elif choice == "2":
            heal = min(20, player.max_hp - player.hp)
            player.hp += heal
            print(f"\n  You rest and recover {heal} HP.")
            continue
        elif choice == "1":
            enemy = create_enemy(difficulty=max(1, player.level))
            print(f"\n  A {enemy.name} appears! HP:{enemy.hp}")
            while enemy.hp > 0 and player.hp > 0:
                try:
                    print(combat_round(player, enemy))
                except EOFError:
                    return
            if player.hp > 0:
                rooms_cleared += 1
        else:
            print("  Invalid choice.")

    print(f"\n  Game Over. Rooms cleared: {rooms_cleared}")
    print(get_player_status(player))


if __name__ == "__main__":
    run_game()
''',

# ------------------------------------------------------------------ #
"inventory": '''\
"""
Inventory Management System
Auto-generated by NEXUS Coder AI
"""

import json
import uuid
from datetime import datetime
from pathlib import Path

DB_FILE = Path("inventory.json")


def _load() -> dict:
    if not DB_FILE.exists():
        return {"products": {}, "movements": [], "categories": {}}
    with open(DB_FILE) as f:
        return json.load(f)


def _save(db: dict) -> None:
    tmp = DB_FILE.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(db, f, indent=2)
    tmp.replace(DB_FILE)


def add_product(name: str, sku: str, price: float,
                qty: int = 0, category: str = "General") -> dict:
    """Add a new product to inventory."""
    db = _load()
    if sku in db["products"]:
        raise ValueError(f"SKU already exists: {sku}")
    product = {
        "id":          str(uuid.uuid4())[:8],
        "sku":         sku,
        "name":        name,
        "category":    category,
        "unit_price":  round(price, 2),
        "stock_qty":   qty,
        "min_stock":   5,
        "is_active":   True,
        "created_at":  datetime.utcnow().isoformat(),
    }
    db["products"][sku] = product
    if qty > 0:
        _record_movement(db, sku, "IN", qty, "Initial stock")
    _save(db)
    return product


def get_product(sku: str) -> dict | None:
    """Retrieve a product by SKU."""
    return _load()["products"].get(sku)


def list_products(category: str = "") -> list:
    """List all active products, optionally filtered by category."""
    db   = _load()
    prods = [p for p in db["products"].values() if p["is_active"]]
    if category:
        prods = [p for p in prods if p["category"] == category]
    return sorted(prods, key=lambda p: p["name"])


def adjust_stock(sku: str, qty: int, movement_type: str = "ADJUST",
                 notes: str = "") -> dict:
    """Adjust stock quantity. movement_type: IN, OUT, ADJUST."""
    db = _load()
    if sku not in db["products"]:
        raise ValueError(f"Product not found: {sku}")
    product = db["products"][sku]
    if movement_type == "OUT" and product["stock_qty"] < qty:
        raise ValueError(f"Insufficient stock. Available: {product['stock_qty']}")
    if movement_type == "IN":
        product["stock_qty"] += qty
    elif movement_type == "OUT":
        product["stock_qty"] -= qty
    else:
        product["stock_qty"] = qty
    _record_movement(db, sku, movement_type, qty, notes)
    _save(db)
    return product


def _record_movement(db: dict, sku: str, mtype: str, qty: int, notes: str):
    db["movements"].append({
        "sku":        sku,
        "type":       mtype,
        "quantity":   qty,
        "notes":      notes,
        "timestamp":  datetime.utcnow().isoformat(),
    })


def low_stock_alerts() -> list:
    """Return products below minimum stock level."""
    return [p for p in _load()["products"].values()
            if p["is_active"] and p["stock_qty"] <= p["min_stock"]]


def get_inventory_value() -> dict:
    """Calculate total inventory value."""
    db      = _load()
    total   = sum(p["stock_qty"] * p["unit_price"]
                  for p in db["products"].values() if p["is_active"])
    return {
        "total_value":    round(total, 2),
        "total_products": len(db["products"]),
        "total_movements": len(db["movements"]),
        "low_stock_count": len(low_stock_alerts()),
    }


def run_repl():
    """Interactive inventory management CLI."""
    print("=" * 55)
    print("  NEXUS Inventory Manager")
    print("  Commands: add, list, stock, value, alerts, exit")
    print("=" * 55)
    while True:
        try:
            cmd = input("inv> ").strip().lower()
            if cmd == "exit":
                break
            elif cmd == "add":
                name     = input("  Name  : ")
                sku      = input("  SKU   : ")
                price    = float(input("  Price : "))
                qty      = int(input("  Qty   : ") or 0)
                product  = add_product(name, sku, price, qty)
                print(f"  Added: [{product['sku']}] {product['name']}")
            elif cmd == "list":
                for p in list_products():
                    print(f"  {p['sku']:<12} {p['name']:<25} Qty:{p['stock_qty']} £{p['unit_price']}")
            elif cmd == "stock":
                sku  = input("  SKU  : ")
                qty  = int(input("  Qty  : "))
                mtype = input("  Type [IN/OUT/ADJUST]: ").upper()
                p    = adjust_stock(sku, qty, mtype)
                print(f"  Updated: {p['name']} → {p['stock_qty']} units")
            elif cmd == "value":
                v = get_inventory_value()
                print(f"  Total Value  : £{v['total_value']}")
                print(f"  Products     : {v['total_products']}")
                print(f"  Low Stock    : {v['low_stock_count']}")
            elif cmd == "alerts":
                for p in low_stock_alerts():
                    print(f"  ⚠ {p['sku']} — {p['name']} — {p['stock_qty']} units left")
            else:
                print("  Unknown command.")
        except (KeyboardInterrupt, EOFError):
            break
        except Exception as e:
            print(f"  Error: {e}")


if __name__ == "__main__":
    run_repl()
''',

# ------------------------------------------------------------------ #
"chat_app": '''\
"""
Chat Server & Client
Auto-generated by NEXUS Coder AI
Uses: Python stdlib (socket, threading)
"""

import socket
import threading
import json
from datetime import datetime


# ── Server ───────────────────────────────────────────────────────── #

class ChatServer:
    """Multi-client TCP chat server."""

    HOST = "0.0.0.0"
    PORT = 9001

    def __init__(self, host: str = HOST, port: int = PORT):
        self.host    = host
        self.port    = port
        self.clients: dict = {}   # {conn: username}
        self._lock   = threading.Lock()
        self._running = False

    def start(self):
        self._running = True
        server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.bind((self.host, self.port))
        server.listen(50)
        print(f"[Server] Listening on {self.host}:{self.port}")
        try:
            while self._running:
                conn, addr = server.accept()
                t = threading.Thread(target=self._handle, args=(conn, addr), daemon=True)
                t.start()
        except KeyboardInterrupt:
            pass
        finally:
            server.close()

    def _handle(self, conn: socket.socket, addr):
        username = f"User_{addr[1]}"
        try:
            raw = conn.recv(256).decode().strip()
            if raw:
                username = raw[:32]
            with self._lock:
                self.clients[conn] = username
            self._broadcast(f"{username} joined the chat.", sender=None)
            while True:
                data = conn.recv(1024)
                if not data:
                    break
                msg = data.decode().strip()
                if msg:
                    self._broadcast(f"[{username}] {msg}", sender=conn)
        except ConnectionResetError:
            pass
        finally:
            with self._lock:
                self.clients.pop(conn, None)
            conn.close()
            self._broadcast(f"{username} left the chat.", sender=None)

    def _broadcast(self, message: str, sender=None):
        packet = (json.dumps({
            "msg":  message,
            "ts":   datetime.utcnow().isoformat(),
        }) + "\n").encode()
        dead = []
        with self._lock:
            for conn in self.clients:
                if conn == sender:
                    continue
                try:
                    conn.sendall(packet)
                except Exception:
                    dead.append(conn)
        for conn in dead:
            with self._lock:
                self.clients.pop(conn, None)

    def get_client_count(self) -> int:
        with self._lock:
            return len(self.clients)


# ── Client ───────────────────────────────────────────────────────── #

class ChatClient:
    """TCP chat client."""

    def __init__(self, host: str = "127.0.0.1", port: int = 9001):
        self.host = host
        self.port = port
        self.sock: socket.socket | None = None

    def connect(self, username: str) -> bool:
        try:
            self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.sock.connect((self.host, self.port))
            self.sock.sendall(username.encode())
            return True
        except Exception as e:
            print(f"[Client] Connection failed: {e}")
            return False

    def listen(self):
        """Read messages from server in background thread."""
        def _recv():
            buf = ""
            while True:
                try:
                    data = self.sock.recv(1024).decode()
                    if not data:
                        break
                    buf += data
                    while "\n" in buf:
                        line, buf = buf.split("\n", 1)
                        try:
                            obj = json.loads(line)
                            print(f"\r  {obj['msg']}\n> ", end="", flush=True)
                        except Exception:
                            pass
                except Exception:
                    break
        t = threading.Thread(target=_recv, daemon=True)
        t.start()

    def send(self, message: str):
        if self.sock:
            self.sock.sendall(message.encode())

    def disconnect(self):
        if self.sock:
            self.sock.close()


def get_server_info() -> dict:
    """Return server connection information."""
    return {"host": "127.0.0.1", "port": 9001, "protocol": "TCP"}


def start_server():
    """Start the chat server."""
    ChatServer().start()


def start_client():
    """Start an interactive chat client."""
    try:
        username = input("Username: ").strip() or "Anonymous"
    except EOFError:
        return
    client = ChatClient()
    if not client.connect(username):
        return
    client.listen()
    print(f"Connected as {username}. Type 'exit' to quit.")
    try:
        while True:
            msg = input("> ").strip()
            if msg.lower() == "exit":
                break
            client.send(msg)
    except (KeyboardInterrupt, EOFError):
        pass
    client.disconnect()


if __name__ == "__main__":
    import sys
    mode = sys.argv[1] if len(sys.argv) > 1 else "server"
    if mode == "client":
        start_client()
    else:
        start_server()
''',

# ------------------------------------------------------------------ #
"ai_system": '''\
"""
AI/ML System
Auto-generated by NEXUS Coder AI
Uses: Python stdlib (statistics, math, random)
"""

import math
import random
import statistics
from dataclasses import dataclass, field
from typing import Any


# ── Feature Engineering ──────────────────────────────────────────── #

def normalise(values: list) -> list:
    """Min-max normalisation to [0, 1]."""
    mn, mx = min(values), max(values)
    rng = mx - mn
    if rng == 0:
        return [0.0] * len(values)
    return [(v - mn) / rng for v in values]


def z_score(values: list) -> list:
    """Standardise values using z-score (mean=0, std=1)."""
    if len(values) < 2:
        return values
    mu  = statistics.mean(values)
    std = statistics.stdev(values)
    if std == 0:
        return [0.0] * len(values)
    return [(v - mu) / std for v in values]


def dot_product(a: list, b: list) -> float:
    """Compute dot product of two vectors."""
    return sum(x * y for x, y in zip(a, b))


def euclidean_distance(a: list, b: list) -> float:
    """Compute Euclidean distance between two vectors."""
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))


# ── k-Nearest Neighbours Classifier ─────────────────────────────── #

@dataclass
class KNNClassifier:
    """Simple k-Nearest Neighbours classifier."""
    k: int = 3
    _X_train: list = field(default_factory=list)
    _y_train: list = field(default_factory=list)

    def fit(self, X: list, y: list):
        """Train the classifier."""
        self._X_train = X
        self._y_train = y
        return self

    def predict(self, X: list) -> list:
        """Predict labels for a list of samples."""
        return [self._predict_one(x) for x in X]

    def _predict_one(self, x: list) -> Any:
        distances = [
            (euclidean_distance(x, xi), yi)
            for xi, yi in zip(self._X_train, self._y_train)
        ]
        distances.sort(key=lambda d: d[0])
        neighbours = [label for _, label in distances[:self.k]]
        return max(set(neighbours), key=neighbours.count)

    def score(self, X: list, y: list) -> float:
        """Return accuracy on a test set."""
        preds   = self.predict(X)
        correct = sum(p == t for p, t in zip(preds, y))
        return correct / len(y)


# ── Linear Regression ────────────────────────────────────────────── #

@dataclass
class LinearRegression:
    """Ordinary Least Squares linear regression."""
    slope:     float = 0.0
    intercept: float = 0.0

    def fit(self, X: list, y: list):
        """Fit model to 1-D feature list X and targets y."""
        n    = len(X)
        mu_x = statistics.mean(X)
        mu_y = statistics.mean(y)
        num  = sum((xi - mu_x) * (yi - mu_y) for xi, yi in zip(X, y))
        den  = sum((xi - mu_x) ** 2 for xi in X)
        self.slope     = num / den if den else 0.0
        self.intercept = mu_y - self.slope * mu_x
        return self

    def predict(self, X: list) -> list:
        """Predict y for a list of X values."""
        return [self.slope * x + self.intercept for x in X]

    def r_squared(self, X: list, y: list) -> float:
        """Return the coefficient of determination R²."""
        preds  = self.predict(X)
        mu_y   = statistics.mean(y)
        ss_res = sum((yi - pi) ** 2 for yi, pi in zip(y, preds))
        ss_tot = sum((yi - mu_y) ** 2 for yi in y)
        return 1 - ss_res / ss_tot if ss_tot else 0.0


# ── Pipeline ─────────────────────────────────────────────────────── #

def train_test_split(X: list, y: list, test_ratio: float = 0.2):
    """Split data into train and test sets."""
    n_test = max(1, int(len(X) * test_ratio))
    idx    = list(range(len(X)))
    random.shuffle(idx)
    test_idx  = set(idx[:n_test])
    X_train   = [X[i] for i in idx if i not in test_idx]
    y_train   = [y[i] for i in idx if i not in test_idx]
    X_test    = [X[i] for i in idx if i     in test_idx]
    y_test    = [y[i] for i in idx if i     in test_idx]
    return X_train, X_test, y_train, y_test


def demo_pipeline():
    """Run a full ML pipeline demonstration."""
    print("=" * 50)
    print("  NEXUS AI System — Demo Pipeline")
    print("=" * 50)

    # Generate synthetic classification data
    random.seed(42)
    X = [[random.gauss(c, 0.5), random.gauss(c, 0.5)]
         for c in [0]*50 + [3]*50]
    y = [0]*50 + [1]*50
    X_tr, X_te, y_tr, y_te = train_test_split(X, y)

    model = KNNClassifier(k=3).fit(X_tr, y_tr)
    acc   = model.score(X_te, y_te)
    print(f"  KNN Classifier — Accuracy: {acc:.1%}")

    # Linear regression on 1-D data
    X_reg = list(range(1, 21))
    y_reg = [2*x + random.gauss(0, 1) for x in X_reg]
    reg   = LinearRegression().fit(X_reg, y_reg)
    r2    = reg.r_squared(X_reg, y_reg)
    print(f"  Linear Regression — R²: {r2:.4f}")
    print(f"  Slope: {reg.slope:.4f}  Intercept: {reg.intercept:.4f}")
    return {"knn_accuracy": acc, "r_squared": r2}


if __name__ == "__main__":
    demo_pipeline()
''',

# ------------------------------------------------------------------ #
"scheduler": '''\
"""
Task Scheduler
Auto-generated by NEXUS Coder AI
"""

import time
import uuid
import threading
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import Callable


@dataclass
class ScheduledJob:
    id:          str
    name:        str
    fn:          Callable
    interval_s:  float
    next_run:    float
    run_count:   int = 0
    error_count: int = 0
    last_result: str = ""
    enabled:     bool = True


class JobScheduler:
    """Fixed-interval job scheduler with error isolation."""

    def __init__(self):
        self._jobs:    dict = {}
        self._lock     = threading.Lock()
        self._running  = False
        self._thread:  threading.Thread | None = None

    def add_job(self, name: str, fn: Callable, interval_s: float) -> str:
        """Register a job. Returns its ID."""
        job_id = str(uuid.uuid4())[:8]
        job    = ScheduledJob(
            id=job_id, name=name, fn=fn,
            interval_s=interval_s,
            next_run=time.monotonic() + interval_s,
        )
        with self._lock:
            self._jobs[job_id] = job
        print(f"[Scheduler] Registered '{name}' every {interval_s}s → ID:{job_id}")
        return job_id

    def remove_job(self, job_id: str) -> bool:
        with self._lock:
            if job_id in self._jobs:
                del self._jobs[job_id]
                return True
        return False

    def enable_job(self, job_id: str, enabled: bool = True):
        with self._lock:
            if job_id in self._jobs:
                self._jobs[job_id].enabled = enabled

    def get_status(self) -> list:
        with self._lock:
            return [
                {
                    "id":          j.id,
                    "name":        j.name,
                    "interval_s":  j.interval_s,
                    "run_count":   j.run_count,
                    "error_count": j.error_count,
                    "enabled":     j.enabled,
                    "last_result": j.last_result,
                }
                for j in self._jobs.values()
            ]

    def start(self):
        """Start the scheduler in a background thread."""
        self._running = True
        self._thread  = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()
        print("[Scheduler] Started.")

    def stop(self):
        """Stop the scheduler."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        print("[Scheduler] Stopped.")

    def _loop(self):
        while self._running:
            now = time.monotonic()
            with self._lock:
                due = [j for j in self._jobs.values()
                       if j.enabled and j.next_run <= now]
            for job in due:
                self._run_job(job)
            time.sleep(0.1)

    def _run_job(self, job: ScheduledJob):
        try:
            result = job.fn()
            job.last_result = str(result)[:100]
            job.run_count  += 1
        except Exception as e:
            job.last_result = f"ERROR: {e}"
            job.error_count += 1
        job.next_run = time.monotonic() + job.interval_s


def get_scheduler() -> JobScheduler:
    """Return a ready-to-use scheduler instance."""
    return JobScheduler()


def run_demo():
    """Demonstrate the scheduler with sample jobs."""
    scheduler = get_scheduler()

    def heartbeat():
        return f"alive at {datetime.utcnow().strftime('%H:%M:%S')}"

    def metrics():
        return f"cpu=ok mem=ok ts={datetime.utcnow().isoformat()}"

    scheduler.add_job("heartbeat", heartbeat, interval_s=2)
    scheduler.add_job("metrics",   metrics,   interval_s=5)
    scheduler.start()

    print("Scheduler running for 12 seconds...")
    time.sleep(12)
    scheduler.stop()

    for s in scheduler.get_status():
        print(f"  {s['name']}: {s['run_count']} runs, {s['error_count']} errors")


if __name__ == "__main__":
    run_demo()
''',

# ------------------------------------------------------------------ #
"file_manager": '''\
"""
File Manager
Auto-generated by NEXUS Coder AI
"""

import os
import shutil
import hashlib
import json
from datetime import datetime
from pathlib import Path


def list_directory(path: str = ".") -> list:
    """List directory contents with metadata."""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Path not found: {path}")
    entries = []
    for item in sorted(p.iterdir()):
        stat = item.stat()
        entries.append({
            "name":       item.name,
            "type":       "dir" if item.is_dir() else "file",
            "size":       stat.st_size,
            "modified":   datetime.fromtimestamp(stat.st_mtime).isoformat(),
            "extension":  item.suffix.lower() if item.is_file() else "",
        })
    return entries


def search_files(root: str, pattern: str) -> list:
    """Recursively search for files matching a glob pattern."""
    return [str(p) for p in Path(root).rglob(pattern)]


def copy_file(src: str, dst: str) -> str:
    """Copy a file and return the destination path."""
    src_path = Path(src)
    if not src_path.is_file():
        raise FileNotFoundError(f"Source not found: {src}")
    dst_path = Path(dst)
    dst_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_path, dst_path)
    return str(dst_path)


def move_file(src: str, dst: str) -> str:
    """Move a file and return the destination path."""
    Path(dst).parent.mkdir(parents=True, exist_ok=True)
    shutil.move(src, dst)
    return dst


def delete_file(path: str, confirm: bool = False) -> bool:
    """Delete a file. Requires confirm=True."""
    if not confirm:
        raise PermissionError("Set confirm=True to delete files.")
    p = Path(path)
    if p.is_file():
        p.unlink()
        return True
    if p.is_dir():
        shutil.rmtree(p)
        return True
    return False


def checksum(filepath: str, algorithm: str = "sha256") -> str:
    """Compute a file checksum."""
    h = hashlib.new(algorithm)
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def create_directory(path: str) -> str:
    """Create a directory and all parents."""
    Path(path).mkdir(parents=True, exist_ok=True)
    return path


def get_disk_usage(path: str = ".") -> dict:
    """Return disk usage statistics for a path."""
    total, used, free = shutil.disk_usage(path)
    return {
        "total_gb": round(total / 1e9, 2),
        "used_gb":  round(used  / 1e9, 2),
        "free_gb":  round(free  / 1e9, 2),
        "used_pct": round(used / total * 100, 1),
    }


def run_repl():
    """Interactive file manager CLI."""
    print("=" * 55)
    print("  NEXUS File Manager")
    print("  Commands: ls, find, copy, move, checksum, disk, mkdir, exit")
    print("=" * 55)
    cwd = "."
    while True:
        try:
            cmd = input(f"fm [{cwd}]> ").strip().split(None, 2)
            if not cmd:
                continue
            action = cmd[0].lower()
            if action == "exit":
                break
            elif action == "ls":
                path  = cmd[1] if len(cmd) > 1 else cwd
                items = list_directory(path)
                for i in items:
                    marker = "/" if i["type"] == "dir" else " "
                    print(f"  {marker}{i['name']:<40} {i['size']:>10} B")
            elif action == "find" and len(cmd) >= 3:
                for f in search_files(cmd[1], cmd[2]):
                    print(f"  {f}")
            elif action == "copy" and len(cmd) >= 3:
                dst = copy_file(cmd[1], cmd[2])
                print(f"  Copied → {dst}")
            elif action == "move" and len(cmd) >= 3:
                dst = move_file(cmd[1], cmd[2])
                print(f"  Moved  → {dst}")
            elif action == "checksum" and len(cmd) >= 2:
                print(f"  {checksum(cmd[1])}")
            elif action == "disk":
                u = get_disk_usage(cmd[1] if len(cmd) > 1 else ".")
                print(f"  Used: {u['used_gb']} GB / {u['total_gb']} GB ({u['used_pct']}%)")
            elif action == "mkdir" and len(cmd) >= 2:
                create_directory(cmd[1])
                print(f"  Created: {cmd[1]}")
            else:
                print("  Unknown command.")
        except (KeyboardInterrupt, EOFError):
            break
        except Exception as e:
            print(f"  Error: {e}")


if __name__ == "__main__":
    run_repl()
''',

# ------------------------------------------------------------------ #
"generic": '''\
"""
Application
Auto-generated by NEXUS Coder AI
"""

import json
import logging
from datetime import datetime
from pathlib import Path

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("nexus-app")


def get_version() -> str:
    """Return the application version."""
    return "1.0.0"


def initialize() -> dict:
    """Initialise the application and return status."""
    logger.info("Application initialising...")
    status = {
        "version":    get_version(),
        "started_at": datetime.utcnow().isoformat(),
        "status":     "ONLINE",
    }
    logger.info(f"Application ready — version {status['version']}")
    return status


def health_check() -> dict:
    """Return current health status."""
    return {
        "status":    "healthy",
        "version":   get_version(),
        "timestamp": datetime.utcnow().isoformat(),
    }


def process(payload: dict) -> dict:
    """Process a generic payload and return result."""
    if not payload:
        raise ValueError("Payload cannot be empty.")
    result = {
        "processed_at": datetime.utcnow().isoformat(),
        "input_keys":   list(payload.keys()),
        "status":       "SUCCESS",
    }
    logger.info(f"Processed payload with keys: {result['input_keys']}")
    return result


def save_state(data: dict, path: str = "state.json") -> str:
    """Persist application state to a JSON file."""
    tmp = Path(path).with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(data, f, indent=2)
    tmp.replace(path)
    return path


def load_state(path: str = "state.json") -> dict:
    """Load application state from a JSON file."""
    p = Path(path)
    if not p.exists():
        return {}
    with open(p) as f:
        return json.load(f)


def run():
    """Main application entry point."""
    status = initialize()
    print(json.dumps(status, indent=2))
    print("\nHealth:", json.dumps(health_check(), indent=2))


if __name__ == "__main__":
    run()
''',

}   # end _TEMPLATES


# ------------------------------------------------------------------ #
# Type Detection                                                        #
# ------------------------------------------------------------------ #

_KEYWORDS: dict = {
    "calculator":    ["calculator", "calc", "arithmetic", "math"],
    "todo_app":      ["todo", "task", "checklist", "reminder", "planner"],
    "web_app":       ["web app", "website", "web application", "portal", "blog", "cms", "dashboard"],
    "rest_api":      ["rest api", "rest", "api", "endpoint", "microservice", "backend", "server"],
    "desktop_gui":   ["desktop", "gui", "window", "tkinter", "form", "native app"],
    "data_analyzer": ["data", "analysis", "analytics", "csv", "report", "statistics", "pipeline"],
    "game":          ["game", "puzzle", "adventure", "quiz", "rpg", "arcade"],
    "inventory":     ["inventory", "stock", "warehouse", "product", "catalogue", "supply"],
    "ai_system":     ["ai", "machine learning", "ml", "neural", "model", "prediction", "classifier"],
    "scheduler":     ["scheduler", "cron", "job", "queue", "task runner"],
    "chat_app":      ["chat", "messenger", "messaging", "socket"],
    "file_manager":  ["file", "directory", "folder", "storage", "organizer"],
}


def _detect_type(goal: str) -> str:
    goal_l = goal.lower()
    scores = {pt: sum(kw in goal_l for kw in kws) for pt, kws in _KEYWORDS.items()}
    best   = max(scores, key=lambda k: scores[k])
    return best if scores[best] > 0 else "generic"


# ------------------------------------------------------------------ #
# CoderAI                                                              #
# ------------------------------------------------------------------ #

class CoderAI:
    """
    NEXUS Universal Code Generation Engine.

    Detects the project type from the goal (or reads it from
    Research AI via Shared Memory) and generates a complete,
    production-grade application from the matching template.

    Supported types
    ---------------
    calculator · todo_app · web_app · rest_api · desktop_gui ·
    data_analyzer · game · inventory · ai_system · scheduler ·
    chat_app · file_manager · generic
    """

    def __init__(self, shared_memory):
        self.memory = shared_memory
        print("[Coder AI] Connected to Shared Memory.")

    def start(self):
        print("[Coder AI] Universal Code Generation Engine Ready.")

    def process_project_task(self, task_id: str):

        key     = f"active_project_{task_id}"
        project = self.memory.read(key)

        if project is None:
            print(f"[Coder AI] Project '{task_id}' not found.")
            return

        goal = project.get("goal", "")
        print(f"[Coder AI] Processing : {task_id}")
        print(f"[Coder AI] Goal       : {goal}")

        # Prefer project_type set by Research AI
        project_type = project.get("project_type") or _detect_type(goal)
        source       = _TEMPLATES.get(project_type, _TEMPLATES["generic"])
        requirements = _REQUIREMENTS.get(project_type, [])

        print(f"[Coder AI] Type       : {project_type}")

        project["code"] = {
            "language":     "Python",
            "version":      "1.0.0",
            "author":       "Coder AI",
            "generated_at": datetime.utcnow().isoformat(),
            "status":       "INITIAL_IMPLEMENTATION_COMPLETE",
            "project_type": project_type,
            "files":        ["main.py"],
            "requirements": requirements,
            "source":       source,
        }

        project["status"]       = "PROGRAMMING_PHASE_COMPLETE"
        project["project_type"] = project_type
        self.memory.write(key, project)

        print(f"[Coder AI] Template   : {project_type}")
        print(f"[Coder AI] Lines      : {len(source.splitlines())}")
        print(f"[Coder AI] Deps       : {requirements or ['none (stdlib only)']}")
        print(f"[Coder AI] Source committed to Shared Memory.")
