"""
NEXUS Builder
Monitoring AI — Observability Engineering Engine

Module ID : MONITOR-001
Version   : 1.0.0

Generates production-grade observability artefacts:
health check script, structured logging configuration,
metrics collector, and alerting rules — all based on
actual project data from Shared Memory.
"""

import os
from datetime import datetime


def _health_check_script(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    arch = project.get("architecture", {})
    return f'''\
"""
Health Check — Auto-generated by NEXUS Monitoring AI
Application: {goal}
"""

import sys
import time
import json
import socket
import sqlite3
from pathlib import Path
from datetime import datetime, timezone

APP_NAME    = "{goal}"
DB_PATH     = Path("data/database.sqlite")
CHECKS      = []
START_TIME  = time.time()


def register(name):
    """Decorator to register a health check."""
    def decorator(fn):
        CHECKS.append((name, fn))
        return fn
    return decorator


@register("application")
def check_application() -> dict:
    """Verify the application module is importable."""
    try:
        import main  # noqa: F401
        return {{"status": "pass", "message": "main.py loaded successfully"}}
    except Exception as err:
        return {{"status": "fail", "message": str(err)}}


@register("database")
def check_database() -> dict:
    """Verify the SQLite database is accessible."""
    if not DB_PATH.exists():
        return {{"status": "warn", "message": "Database file not found — will be created on first run"}}
    try:
        conn = sqlite3.connect(str(DB_PATH))
        conn.execute("SELECT 1")
        conn.close()
        return {{"status": "pass", "message": f"Database responsive at {{DB_PATH}}"}}
    except Exception as err:
        return {{"status": "fail", "message": str(err)}}


@register("filesystem")
def check_filesystem() -> dict:
    """Verify write access to the working directory."""
    probe = Path(".nexus_probe")
    try:
        probe.write_text("ok")
        probe.unlink()
        return {{"status": "pass", "message": "Filesystem writable"}}
    except Exception as err:
        return {{"status": "fail", "message": str(err)}}


@register("memory")
def check_memory() -> dict:
    """Report available memory."""
    try:
        import resource
        usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        return {{"status": "pass", "message": f"RSS: {{usage}} KB"}}
    except Exception:
        return {{"status": "pass", "message": "Memory check not supported on this platform"}}


def run_checks() -> dict:
    results = {{}}
    overall = "pass"

    for name, fn in CHECKS:
        try:
            result = fn()
        except Exception as err:
            result = {{"status": "fail", "message": str(err)}}

        results[name] = result

        if result["status"] == "fail":
            overall = "fail"
        elif result["status"] == "warn" and overall == "pass":
            overall = "warn"

    return {{
        "status":    overall,
        "app":       APP_NAME,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "uptime_s":  round(time.time() - START_TIME, 3),
        "checks":    results,
    }}


if __name__ == "__main__":
    report = run_checks()
    print(json.dumps(report, indent=2))
    sys.exit(0 if report["status"] in ("pass", "warn") else 1)
'''


def _logger_config(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    return f'''\
"""
Logging Configuration — Auto-generated by NEXUS Monitoring AI
Application: {goal}
"""

import logging
import logging.config
import json
from datetime import datetime, timezone


class JSONFormatter(logging.Formatter):
    """Structured JSON log formatter."""

    def format(self, record: logging.LogRecord) -> str:
        log_entry = {{
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level":     record.levelname,
            "logger":    record.name,
            "message":   record.getMessage(),
            "module":    record.module,
            "line":      record.lineno,
        }}
        if record.exc_info:
            log_entry["exception"] = self.formatException(record.exc_info)
        return json.dumps(log_entry)


LOGGING_CONFIG = {{
    "version":          1,
    "disable_existing_loggers": False,
    "formatters": {{
        "json": {{
            "()": "__main__.JSONFormatter",
        }},
        "simple": {{
            "format": "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        }},
    }},
    "handlers": {{
        "console": {{
            "class":     "logging.StreamHandler",
            "formatter": "simple",
            "level":     "INFO",
        }},
        "file": {{
            "class":       "logging.handlers.RotatingFileHandler",
            "filename":    "logs/app.log",
            "maxBytes":    10_485_760,   # 10 MB
            "backupCount": 5,
            "formatter":   "json",
            "level":       "DEBUG",
        }},
    }},
    "root": {{
        "handlers": ["console", "file"],
        "level":    "DEBUG",
    }},
}}


def setup_logging():
    """Apply logging configuration."""
    import os
    os.makedirs("logs", exist_ok=True)
    logging.config.dictConfig(LOGGING_CONFIG)
    return logging.getLogger("{goal}")


if __name__ == "__main__":
    logger = setup_logging()
    logger.info("Logging system initialised.")
    logger.debug("Debug mode active.")
    logger.warning("This is a warning.")
'''


def _metrics_script(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    return f'''\
"""
Metrics Collector — Auto-generated by NEXUS Monitoring AI
Application: {goal}
"""

import time
import json
import threading
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

METRICS_FILE = Path("logs/metrics.json")
METRICS_FILE.parent.mkdir(parents=True, exist_ok=True)

_counters:   dict = defaultdict(int)
_gauges:     dict = {{}}
_histograms: dict = defaultdict(list)
_lock = threading.Lock()


def increment(name: str, value: int = 1, tags: dict | None = None):
    """Increment a counter metric."""
    key = _key(name, tags)
    with _lock:
        _counters[key] += value


def gauge(name: str, value: float, tags: dict | None = None):
    """Set a gauge metric to an absolute value."""
    key = _key(name, tags)
    with _lock:
        _gauges[key] = value


def observe(name: str, value: float, tags: dict | None = None):
    """Record a histogram observation."""
    key = _key(name, tags)
    with _lock:
        _histograms[key].append(value)


def timer(name: str, tags: dict | None = None):
    """Context manager to time a block of code."""
    class _Timer:
        def __enter__(self_):
            self_._start = time.perf_counter()
            return self_
        def __exit__(self_, *_):
            duration_ms = (time.perf_counter() - self_._start) * 1000
            observe(name, duration_ms, tags)
    return _Timer()


def snapshot() -> dict:
    """Return a point-in-time snapshot of all metrics."""
    with _lock:
        hist_summary = {{}}
        for k, vals in _histograms.items():
            if vals:
                hist_summary[k] = {{
                    "count": len(vals),
                    "min":   round(min(vals), 4),
                    "max":   round(max(vals), 4),
                    "avg":   round(sum(vals) / len(vals), 4),
                }}
        return {{
            "app":        "{goal}",
            "timestamp":  datetime.now(timezone.utc).isoformat(),
            "counters":   dict(_counters),
            "gauges":     dict(_gauges),
            "histograms": hist_summary,
        }}


def flush():
    """Write current metrics snapshot to disk."""
    data = snapshot()
    with open(METRICS_FILE, "w") as f:
        json.dump(data, f, indent=2)
    return data


def _key(name: str, tags: dict | None) -> str:
    if not tags:
        return name
    tag_str = ",".join(f"{{k}}={{v}}" for k, v in sorted(tags.items()))
    return f"{{name}}{{{{{tag_str}}}}}"


if __name__ == "__main__":
    # Demo: record some metrics
    increment("requests_total", tags={{"method": "GET"}})
    increment("requests_total", tags={{"method": "POST"}})
    gauge("active_connections", 42)
    with timer("response_time_ms"):
        time.sleep(0.01)
    data = flush()
    print(json.dumps(data, indent=2))
'''


def _alert_rules(project: dict) -> str:
    goal = project.get("goal", "NEXUS Application")
    return json_alert_rules(goal)


def json_alert_rules(goal: str) -> str:
    import json as _json
    rules = {
        "app": goal,
        "generated_at": datetime.utcnow().isoformat(),
        "rules": [
            {
                "name":      "HealthCheckFailing",
                "condition": "health_status == 'fail'",
                "severity":  "CRITICAL",
                "message":   "Application health check is failing.",
                "action":    "Page on-call engineer immediately.",
            },
            {
                "name":      "HighErrorRate",
                "condition": "error_rate_5m > 0.05",
                "severity":  "HIGH",
                "message":   "Error rate exceeds 5% over 5 minutes.",
                "action":    "Check application logs.",
            },
            {
                "name":      "SlowResponses",
                "condition": "avg_response_time_ms > 1000",
                "severity":  "MEDIUM",
                "message":   "Average response time exceeds 1 second.",
                "action":    "Investigate performance bottlenecks.",
            },
            {
                "name":      "DatabaseDown",
                "condition": "database_health == 'fail'",
                "severity":  "CRITICAL",
                "message":   "Database connection failed.",
                "action":    "Check database server and connection string.",
            },
            {
                "name":      "DiskSpaceLow",
                "condition": "disk_free_percent < 10",
                "severity":  "HIGH",
                "message":   "Disk space below 10%.",
                "action":    "Clean up logs and old deployments.",
            },
        ]
    }
    return _json.dumps(rules, indent=2)


class MonitoringAI:
    """
    NEXUS Observability Engineer.

    Generates production-ready monitoring artefacts:
    health check, logging configuration, metrics collector,
    and alerting rules — written to the deployment folder.
    """

    def __init__(self, shared_memory, deployment_root: str = "deployments"):
        self.memory          = shared_memory
        self.deployment_root = deployment_root
        print("[Monitoring AI] Connected to Shared Memory.")

    def start(self):
        print("[Monitoring AI] Observability Engineering Engine Ready.")

    def process_project_task(self, task_id: str):

        key     = f"active_project_{task_id}"
        project = self.memory.read(key)

        if project is None:
            print("[Monitoring AI] Project not found.")
            return

        print(f"[Monitoring AI] Generating observability artefacts: {task_id}")

        goal_slug = project.get("goal", "project").lower().replace(" ", "_")[:40]
        folder    = os.path.join(self.deployment_root, f"{task_id}_{goal_slug}")
        mon_dir   = os.path.join(folder, "monitoring")
        os.makedirs(mon_dir, exist_ok=True)

        artefacts = {
            os.path.join(mon_dir, "health_check.py"):  _health_check_script(project),
            os.path.join(mon_dir, "logger_config.py"): _logger_config(project),
            os.path.join(mon_dir, "metrics.py"):        _metrics_script(project),
            os.path.join(mon_dir, "alerts.json"):       _alert_rules(project),
        }

        written = []
        for path, content in artefacts.items():
            with open(path, "w") as f:
                f.write(content)
            written.append(os.path.basename(path))

        mon_report = {
            "generated_at": datetime.utcnow().isoformat(),
            "artefacts":    written,
            "monitoring_dir": mon_dir,
        }

        project["monitoring"] = mon_report
        project["status"]     = "MONITORING_COMPLETE"
        self.memory.write(key, project)

        for a in written:
            print(f"[Monitoring AI]   ✓ {a}")
